name: App Bug Report
description: Submit an issue encountered within the project.
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue. Please provide the following details
        regarding the bug.
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug.
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      description: Please provide a step-by-step guide to reproduce the error.
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
